/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import java.util.Collections;

/**
 *
 * To start the application:
 * ./gradlew build
 * java -jar ./L01-gradle/build/libs/gradleHelloWorld-0.1.jar
 *
 * To unzip the jar:
 * unzip -l L01-gradle.jar
 * unzip -l gradleHelloWorld-0.1.jar
 *
 */
public class App {
    public static void main(String... args) {
        System.out.println("TEST - addAll");
        DIYArrayList<String> first_list =new DIYArrayList<>();
        for (int i=0;i<20;i++){
            first_list.add("first list number "+String.valueOf(i));
        }
        DIYArrayList<String> second_list =new DIYArrayList<>();
        for (int i=0;i<20;i++){
            second_list.add("second list number "+String.valueOf(i));
        }
        first_list.addAll(second_list);
        for (String item:first_list){
            System.out.println(item);
        }
        // test copy
        System.out.println("TEST - copy");
        DIYArrayList<String> first_list2 =new DIYArrayList<>();
        for (int i=0;i<20;i++){
            first_list2.add("first list number "+String.valueOf(i));
        }
        DIYArrayList<String> second_list2 =new DIYArrayList<>();
        for (int i=0;i<10;i++){
            second_list2.add("second list number "+String.valueOf(i));
        }
        // copy
        Collections.copy(first_list2, second_list2);
        for (String item:first_list2){
            System.out.println(item);
        }

        /// test sort
        System.out.println("TEST - sort");
        DIYArrayList<Integer> src =new DIYArrayList<>();
        for (int i=0;i<20;i++){
            src.add((int)(Math.random() * ( 100 )));
        }
        System.out.println("unsort list");
        for (Integer item:src){
            System.out.println(item.toString());
        }
        /// SORT
        System.out.println("sort list");
        Collections.sort(src);
        for (Integer item:src){
            System.out.println(item.toString());
        }
    }
    
}
