/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import java.util.Collections;

public class App {
    public static void main(String... args) {
        System.out.println("Start test unit");
        DIYTestUnit testUnit=new DIYTestUnit();
        testUnit.run("ru.otus.ArrayListTest");

    }
}
